### PR TITLE
Sqlite pragmas

### PR DESCRIPTION
**Pull request by hackaugusto**
Each pragma has a really short description and links to the authoritative documentation. This basically enables optimizations for sqlite databases used by a single application

### CODE REVIEW

**Comment by hackaugusto** [comment]
> did you add this out of performance considerations (have you benchmarked it), or for ensuring single client mode?

I have not, I only executed some tests locally. My idea was actually to open the PR and check the time it takes to run the tests on the CI, but I don't have huge expectations performance wise on this.

**Comment by LefterisJP** [comment]
Hm DB upgrade `test_upgrade_v16_to_v170` uni tests failed on this one: https://circleci.com/gh/raiden-network/raiden/21360?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hackaugusto** [comment]
The tests failures were because of bad connection management, pretty much none of the tests were closing the connections. This is now fixed.

**Comment by LefterisJP** [comment]
There is still some unit test failing: https://circleci.com/gh/raiden-network/raiden/22676?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by rakanalh** [comment]
@hackaugusto i updated the PR to fix connection issues. If you're ok with my changes, feel free to merge this PR.

**Pull request merged**
