### PR TITLE
remove tester from the test suite

### PR DESCRIPTION
**Pull request by hackaugusto**

### CODE REVIEW

**Comment by LefterisJP** [comment]
@hackaugusto looks good to me. So a PR to also remove the tester source code from the repo would follow I guess?

**Comment by hackaugusto** [comment]
@LefterisJP I'm not working on it right now, but yes we can remove it from the code base, as long as we use tester directly to build the genesis file use for testing.

**Comment by palango** [comment]
What's the reason for removing this?

**Comment by LefterisJP** [comment]
@palango tests sometimes fail due to unknown reasons deep in the tester implementation. Also maintaining multiple testing frameworks is hard.

**Pull request merged**
