### PR TITLE
Move flake8 out of default tox command

### PR DESCRIPTION
**Pull request by LefterisJP**
@hackaugusto Please have a look.

### CODE REVIEW

**Comment by hackaugusto** [comment]
I left flake8 there to enforce the coding standards, but I have nothing against moving it to it's own command.

by the way, I didn't realize but the `flake8 .` executions are far from ideal, I missed that in the PR #222 rebase, it should be as you have done.

**Comment by LefterisJP** [comment]
I think it's a nice thing to enforce style but I am afraid it may eat into our build times. More concerned I was with the fact that since it found style violations it returned error exit code and thus the rest of the tests did not execute.

I believe that at least for now it could be an optional tox target, but I am totally open to suggestions. Most important thing is to not fail the build if there are errors.

**Comment by LefterisJP** [comment]
And lo and behold! It has an argument for that. `--exit-zero`   :)

**Comment by LefterisJP** [comment]
@hackaugusto I made it not fail the build but I think that it should stay as its own target, since if it does not fail the build it makes no sense to have it run in every run.

But having it in tox is really nice since while we are developing we can just do `tox -e flake8` and get a nice report.

Can you please review the PR?

**Pull request merged**
