### PR TITLE
Gas price ropsten

### PR DESCRIPTION
**Pull request by hackaugusto**
Raiden is simply not working on Ropsten with the 20 shannon gas price, since we are not supporting any other network this just adds the default to 200 shannon so that people can use Raiden with less friction.

Builds on: #1097

### CODE REVIEW

**Comment by LefterisJP** [comment]
Can't we also just use the [`eth_gasPrice`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gasprice) RPC call, which is determined by the median price of the `X` last blocks as a default value? It's definitely superior to a hard-coded value.

**Comment by hackaugusto** [comment]
Sure, will change it.

**Comment by LefterisJP** [comment]
Looks good to me, but since this PR also introduces a change to the logic (we spend more gas with each tx) can you add an entry to the changelog?

**Comment by hackaugusto** [comment]
done

**Pull request closed without merging**
