### PR TITLE
update coincurve

### PR DESCRIPTION
**Pull request by ofek**
https://github.com/ofek/coincurve#710

### CODE REVIEW

**Comment by ulope** [comment]
@ofek: Do you want to update the PR to go directly to 7.1.0 now?

**Comment by ofek** [comment]
Sure! Done.

**Comment by LefterisJP** [comment]
@ofek can you squash the 2 commits into one?

**Comment by ofek** [comment]
@LefterisJP Done. :slightly_smiling_face:

**Pull request merged**
