### PR TITLE
No need to subclass from object in Py3.

### PR DESCRIPTION
**Pull request by nlsdfnbch**
Hence, remove that requirement from the
styleguide in CONTRIBUTING.md.

### CODE REVIEW

**Comment by hackaugusto** [comment]
@nlsdfnbch could you also enable the pytest warning named `useless-object-inheritance` and fix any other pending errors?

@LefterisJP and @palango if you guys want to vote for or against this, I think it would be a good time.

**Comment by LefterisJP** [comment]
We already use that in some places .. I know it's no longer needed in python3 but I still tend to do it just out of python2 compatibility habit.

Not for or against this. Just neutral. But if you want to change this, then you should do what @hackaugusto suggested and change it all over the codebase.

**Comment by nlsdfnbch** [comment]
@LefterisJP afait compatibility with py2 shouldn't be a concern though? The docs clearly state it's a Py3.7+ project :man_shrugging:. Will add the linter rule and fix as requested.

**Comment by LefterisJP** [comment]
@nlsdfnbch definitely not a concern for Raiden. I simply stated why it's still there.
But Niels, please don't have branch merge commits in the history. Can yo rebase the merge away?

**Comment by nlsdfnbch** [comment]
@LefterisJP merge commit? what merge commit?[ I dont know what you're talking about.](https://media.giphy.com/media/13d2jHlSlxklVe/giphy.gif)

**Comment by LefterisJP** [comment]
Hahaah I see what you did there ^_^

**Pull request merged**
