### PR TITLE
Use a configuration file in order to persist configuration changes

### PR DESCRIPTION
**Pull request by dilatebrave**
Fix: #1366 

- The configuration file should use the TOML format
- Configuration file should be loaded at startup of the application
- The order of precedence for config options should be the following, listed from higher to lower precedence:
    1. Explicitly given CLI options / arguments
    2. Config file values
    3. CLI defaults

### CODE REVIEW

**Comment by ulope** [comment]
Thanks a lot for your work @dilatebrave!
Unfortunately, the requirements were phrased a bit misunderstandable.

Could you please take a look at the updated issue description and make sure that the code behaves that way (i.e. not overwriting explicitly given CLI values with config file values).

**Comment by vs77bb** [comment]
Hi @dilatebrave have you been able to give the updates a look?

**Comment by dilatebrave** [comment]
@ulope --- i rebased with upstream/stagging that messing up this PR, please review this PR https://github.com/raiden-network/raiden/pull/1668
@vs77bb @ulope --- sorry for taking so long, somehow i've just read the first sentence and thought this issue was done >.<

**Comment by palango** [comment]
@dilatebrave You can update PRs by pushing to your branch. I'll close this one in favour of #1668

**Pull request closed without merging**
