### PR TITLE
Tox envs

### PR DESCRIPTION
**Pull request by hackaugusto**
This splits the `devenv` into three new envs, the intent is to run the tests in paralle with `detox` tool. 

Running the tests sequentially with `tox`:
```
time tox -e unit,smart_contracts,integration
tox -e unit,smart_contracts,integration  216.70s user 6.07s system 81% cpu 4:34.52 total
```

Running these envs in parallel with detox:
```
time detox -e unit,smart_contracts,integration
detox -e unit,smart_contracts,integration  186.64s user 3.38s system 174% cpu 1:49.11 total
```

This PR is built on top of #220

### CODE REVIEW

**Comment by hackaugusto** [comment]
this is not for travis, this is for local development.

for travis check the pr #221

**Comment by LefterisJP** [comment]
All right looks good to me ... needs a rebase though.

**Comment by hackaugusto** [comment]
+r

**Comment by hackaugusto** [comment]
retry

**Comment by hackaugusto** [comment]
retry

**Comment by LefterisJP** [comment]
This PR closes #220 too

**Pull request merged**
