### PR TITLE
Revert "Update to latest geth and parity"

### PR DESCRIPTION
**Pull request by hackaugusto**
Reverts raiden-network/raiden#5382

Parity setup is flaky, leading integration tests failures.

### CODE REVIEW

**Comment by fredo** [comment]
looks like the error setup up happens at geth as well 

https://circleci.com/gh/raiden-network/raiden/100905#tests/containers/17

**Comment by palango** [comment]
> looks like the error setup up happens at geth as well
> 
> https://circleci.com/gh/raiden-network/raiden/100905#tests/containers/17

Are we sure it's related to the new node versions?

**Comment by hackaugusto** [comment]
> https://circleci.com/gh/raiden-network/raiden/100905#tests/containers/17

This one looks like a problem with Matrix, not geth.

**Comment by fredo** [comment]
> > https://circleci.com/gh/raiden-network/raiden/100905#tests/containers/17
> 
> This one looks like a problem with Matrix, not geth.

indeed, the parity test branch shows similiar errors to the ones I experienced though 
https://circleci.com/gh/raiden-network/raiden/100906#tests/containers/24

**Comment by fredo** [comment]
> > looks like the error setup up happens at geth as well
> > https://circleci.com/gh/raiden-network/raiden/100905#tests/containers/17
> 
> Are we sure it's related to the new node versions?

Errors for the partiy part started happening after rebasing to the commit of updating parity

**Pull request merged**
