### PR TITLE
Fix serialization of BlockTimeout and TokenAmount

### PR DESCRIPTION
**Pull request by palango**
## Description

Fixes: #5389

Add `BlockTimeout` and `TokenAmount` to the marshmallow data type mapping.

@andrevmatos @kelsos @nephix This changes the wire format of the `PFSFeeUpdate` message and other messages that include values of these types. Just so you are aware of that in the light client.

## PR review check list

Quality check list that cannot be automatically verified.

- Safety
    - [ ] The changes respect the necessary conditions for safety (https://raiden-network-specification.readthedocs.io/en/latest/smart_contracts.html#protocol-values-constraints)
-  Code quality
    - [ ] Error conditions are handled
    - [ ] Exceptions are propagated to the correct parent greenlet
    - [ ] Exceptions are correctly classified as recoverable or unrecoverable
- Compatibility
    - [ ] State changes are forward compatible
    - [ ] Transport messages are backwards and forward compatible
- Commits
    - [ ] Have good messages
    - [ ] Squashed unecessary commits
- If it's a bug fix:
    - Regression test for the bug
        - [ ] Properly covers the bug
        - [ ] If an integration test is used, it could not be written as a unit test
- Documentation
    - [ ] A new CLI flag was introduced, is there documentation that explains usage?
- Specs
    - [ ] If this is a protocol change, are the specs updated accordingly? If so, please link PR from the specs repo.
- Is it a user facing feature/bug fix?
    - [ ] Changelog entry has been added

### CODE REVIEW

**Comment by andrevmatos** [comment]
Thank you, @palango .
I see this change makes these number fields be [de]serialized to/from strings, right?
We don't do `PFSFeeUpdate`, only `PFSCapacityUpdate`, and our JSON codec utilities can decode [Big]Numbers from both JSON numbers & strings, although it usually encodes to `number`s.
Does your change makes PFS fail to decode our messages if it receives a `number` instead of a `string` for these type of fields? Can't the deserialization be made to support both, even if they're encoded to strings?

**Comment by palango** [comment]
> Can't the deserialization be made to support both, even if they're encoded to strings?

It can, but I'm not sure if it is clever because it might hide bugs. So my first reaction is to be strict, but why did you decide to support both in the LC?

**Comment by andrevmatos** [comment]
Because, when we first implemented it, most of the integers in Raiden were being serialized as JSON `number`, and JavaScript has a limited precision of 2^53 in these cases, we needed to decode them to `BigNumber`s, and our algorithm happen to parse the string representation to avoid the precision loss, therefore it supported decoding from both, BUT at the time ints were encoded to JSON `number`s and therefore we needed to encode them to numbers as well.

I'd say it would not hide bugs, since python don't lose precision there, and the data type should be declared on the serialization schema instead of relying on whatever comes from the JSON object, so if it can decode to the right type from both source types, it wouldn't matter.

The strict way makes us need to keep track to what (string or number) **each** of the several **small** and **big** numbers are **encoded to**, to comply precisely on the LC, or taking the risk of having a message rejected just because Raiden expected a **number** to be encoded as **string** in the JSON message, and we encoded all numbers as a **number**.

**Comment by palango** [comment]
> The strict way makes us need to keep track to what (string or number) each of the several small and big numbers are encoded to, to comply precisely on the LC, or taking the risk of having a message rejected just because Raiden expected a number to be encoded as string in the JSON message, and we encoded all numbers as a number.

I see. So you're OK with us using strict string-or-int types in raiden and the services, or do you think we should have both?

**Comment by andrevmatos** [comment]
I'm ok with enforcing strings everywhere, enforcing numbers everywhere, or **if** mixing them in the message, having non-strict decoders (number deserializer which ensures number type as output [int] but accepting both numbers and strings as input).
I'm not ok with heterogenous (even if it's just a single case) encoding and strict decoding.

**Comment by andrevmatos** [comment]
PS: currently, there're several numeric fields currently being encoded as numbers, and others being encoded as strings. Just peek at matrix's `#raiden_goerli_path_finding:transport04.raiden.network`, and you can see even amount fields (big) being encoded as numbers while others expectedly small (as `chain_id`) being encoded as strings.

**Comment by andrevmatos** [comment]
IMHO, the best and least change-requiring approach would be to allow heterogenous numbers, with non-strict decoding. This way, there's no need to change all current fields, each client can decide which numbers to encode as numbers or strings (or even encode all in one way or another, since JSON standard doesn't impose a precision limit on numbers), and if they all can decode both in any numeric field, it'll have maximum compatibility.
For reference, LC currently assumes the above approach, and encodes all numbers as JSON `number`.

**Pull request merged**
