### PR TITLE
Use local time in logs

### PR DESCRIPTION
**Pull request by palango**
Use the local time of the PC for the logs.

### CODE REVIEW

**Comment by palango** [comment]
> I don't recall if we have a specific reason for using UTC.

@pcppcp Do you know?

**Comment by pcppcp** [comment]
Please, keep it UTC.
For software used world-wide, it's useful to sync the time to one timezone. If you need to compare i.e. a raiden transfer between nodes in different timezones, and you get logs with local time, it's a huge PITA to wrap your head around the order of the events (for example Indian time is +5:30)

**Comment by palango** [comment]
Ok, we thought that happened by accident, but as you have a reason I'm closing this.

**Comment by LefterisJP** [comment]
I had missed this PR. 100% with @pcppcp. In the software world not using UTC or mixing UTC and local time is one of the most well known source of bugs and headaches. Just keep everything in UTC always.

**Pull request closed without merging**
