### PR TITLE
Use raiden-contracts 0.27.0

### PR DESCRIPTION
**Pull request by pirapira**
The ABI changed, so currently I'm expecting a CI failure.

### CODE REVIEW

**Comment by pirapira** [comment]
@karlb l I get `E   pytest.PytestDeprecationWarning: the ``pytest.config`` global is deprecated.  Please use ``request.config`` or ``pytest_configure`` (if you're a pytest plugin) instead.`  on 
```
    @pytest.mark.skipif(getattr(pytest, "config").getvalue("usepdb"), reason="test fails with pdb")
```
Do you have a good suggestion how to replace `pytest.config`?  Docs say use `request.config` but I don't know how do I access the `request` fixture here.

**Comment by nlsdfnbch** [comment]
I'm not 100% certain, but I believe using fixtures in the `pytest.mark` decorators isn't possible. There's an ancient github issue requesting a similar feature (fixtures in `mark.parametrize`), but that hasn't seen much attention - especially since passing the name of fixtures as strings in the `argvalues` of `mark.parametrize` now loads the related fixture (as of 3.0, I think).

Which, afaics, leaves you with two options:
1. Delve into the hook system rabbit hole and implement this logic yourself
2. Instead of decorating with skipif call `pytest.skip` inside the test:
```python
def test_something(request):
    if request.config.get("usepdb", False):
        pytest.skip("Test fails with pdb enabled.")
```
I suggest going with option 2. ;)

**Comment by pirapira** [comment]
I suddenly realized that `get_random_pfs()` function needs to be supported.

So ServiceRegistry must have an array of addresses that have ever made a deposit.

**Comment by pirapira** [comment]
I'll reuse this branch for `contract-0-28-0`.

**Comment by pirapira** [comment]
The missing pieceis tracked in https://github.com/raiden-network/raiden-contracts/issues/1139

**Pull request closed without merging**
