### PR TITLE
Changed http:// to https:// on some links

### PR DESCRIPTION
**Pull request by sandakersmann**
Changed http:// to https:// on some links in README.rst

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hey @sandakersmann we now have a CLA that needs to be signed in order to accept contributions from external people. If you can sign it then we can merge your PR.

**Comment by palango** [comment]
Thanks for your PR @sandakersmann  . We now have our CLA in place. Please rebase your PR, sign the CLA and add the `Please review` tag to this PR.

**Comment by sandakersmann** [comment]
@LefterisJP It's done :)

**Comment by palango** [comment]
Can you please rebase your changes on top of master

**Comment by sandakersmann** [comment]
I can resubmit

**Comment by palango** [comment]
It's fine. I just clicked this *Update* button in GitHub which unfortunately merges master. Feel free to resubmit.

**Comment by sandakersmann** [comment]
It's done :)

**Pull request closed without merging**
