### PR TITLE
Use 'binascii.unhexlify' for py3 compatibility

### PR DESCRIPTION
**Pull request by palango**
Python 3 doesn't have the `decode` method on the `str` type.

### CODE REVIEW

**Comment by palango** [comment]
Do we want to merge stuff like this right away or wait for more progress.

**Comment by hackaugusto** [comment]
I wonder if we should just use [binascii](https://docs.python.org/2.7/library/binascii.html) directly.

Opinions?

**Comment by palango** [comment]
Or our own utility function?

**Comment by andrevmatos** [comment]
I think it's nice to start merging these kind of PR. We should create a tag for py3 preparation requests though.
Another thing, which is very important IMHO, is to keep in mind, and maybe create a internal pattern, for the differences between `bytes` and `str`. Raiden uses binary represetation in a lot of places, including addresses. Those should become `bytes` in py3 version, and be decoded only for to `str` when needed a human-readable or serializable [hex] representation. Python2 is very messy on this sense (everything is str, some encoded, some decoded), but we should enforce a good pattern on python3.

**Comment by hackaugusto** [comment]
> Or our own utility function?

Well, that would just wrap binascii, wouldn't it?

@andrevmatos I'm not sure what you're trying to say, but check this out: https://github.com/raiden-network/raiden/blob/3cb5d526f511707d4b4d0fa2840aa60d1cc861c6/CONTRIBUTING.md#encoding

**Comment by hackaugusto** [comment]
@palango Btw, I'm talking about the binascii because that is what pyethereum uses for py3 (it reexports the utility from the rlp library), and that is also available for py2

**Comment by palango** [comment]
I thought about adding the following to `raiden.utils`, think it's a bit clearer:
```py
def decode_hex(hexstr):
    return binascii.unhexlify(hexstr)
```

**Comment by andrevmatos** [comment]
@hackaugusto I'm talking about the most (for me, and I think it'd be what `2to3` would do) natural thinking in these binary -> str conversions, which is to keep using string type internally, while most of these binary representations must be converted to `bytes`, and to `str` on the inputs/outputs.

**Comment by hackaugusto** [comment]
Superseeded by #1158

**Pull request closed without merging**
