### PR TITLE
WIP: Py3 conversion

### PR DESCRIPTION
**Pull request by palango**
WIP

### CODE REVIEW

**Comment by LefterisJP** [comment]
Wow that's a lot of tiny commits. Please do squash some of them together. Anything that can be grouped together logically belongs in one commit.

**Comment by palango** [comment]
Yeah, will clean the history up once the tests pass. For now I find it easier to have small units.

**Comment by LefterisJP** [comment]
@palango perhaps until you are completely ready add a [skip ci] into your commits? Unless you are actually trying Travis with every commit intentionally. Otherwise all travis jobs go into this PR.

**Comment by pcppcp** [comment]
You can also use a free Travis instance for your private repo/fork, add `[skip ci]` as Lefteris suggested and trigger builds manually.

**Comment by palango** [comment]
That sounds reasonable :)

**Pull request closed without merging**
