### PR TITLE
Remove the pytest requirement in smoketest

### PR DESCRIPTION
**Pull request by palango**
Bring back `pytest` as of https://github.com/raiden-network/raiden/pull/1175#issuecomment-349830900

### CODE REVIEW

**Comment by LefterisJP** [comment]
@konradkonrad Can you remind us why we need pytests in the requirements, and by extentions tests included in the release?

**Comment by konradkonrad** [comment]
`smoketest` shares some infrastructure with the common test framework: 
https://github.com/raiden-network/raiden/blob/master/raiden/tests/utils/smoketest.py#L28-L29

I don't think, we need `pytest` as a runtime dependency, however importing from `raiden/tests/...` will in most cases ask for a `pytest` import.

To get rid of this dependency, one could factor the smoketest and the shared test utilities out of the `raiden.test` module.

**Comment by palango** [comment]
I moved the `create_tester_state` function to the `tests/util/tester.py` module to get rid of the `pytest`dependency in smoketest.

I'm not really sure why `tester.processblock` worked before, so have an eye on this during review.

**Comment by LefterisJP** [comment]
Looks good to me.

@palango Can you elaborate a bit on:

> I'm not really sure why tester.processblock worked before, so have an eye on this during review.

**Comment by palango** [comment]
Before my change the `tester.processblock.apply_transaction` function was patched. When I commit my changes I got errors in travis: `'module' object has no attribute 'processblock'`

See https://travis-ci.org/raiden-network/raiden/jobs/314777309#L1111

**Comment by LefterisJP** [comment]
That's strange. Could be some difference in the way pyethereum is structured now? 
At least in my local copy of pyethereum inside the venv ethereum tester calls processblock inside it so it should be referencing the same function.

**Pull request merged**
