### PR TITLE
Rename payment network

### PR DESCRIPTION
**Pull request by karlb**
What is called "payment network" in Raiden is called token network registry in the contracts and services. That name is more descriptive, so use it in the Raiden code base to to achieve more consistency.

This changes API endpoints, so changes will be necessary elsewhere
- [x] SP
- [x] web UI
- [ ] docs

### CODE REVIEW

**Comment by palango** [comment]
@kelsos , @manuelwedler, @nlsdfnbch Is this endpoint used in the webUI/ scenario player? https://github.com/raiden-network/raiden/pull/4564/files#diff-8a975e5d87b5ba8673403e4786aae22dR147

**Comment by kelsos** [comment]
@palango The WebUI should not touch the debug endpoints anymore. I recall removing them completely because the maintenance cost was high (a lot of changes really often) and the target for the WebUI is not strictly developers anymore.

**Comment by manuelwedler** [comment]
Yes I can confirm that. The WebUI does not touch these endpoints.

**Comment by palango** [comment]
I cannot find usage of the mentioned API in the SP either.

**Pull request merged**
