### PR TITLE
untangle and cleanup raiden.mtree

### PR DESCRIPTION
**Pull request by schmir**
The previous implementation of merkleroot was hard to understand, since
it tried to do several things at the same time.

I've tried to untangle that and now we've got separate functions to
- iterate pairwise over a list of elements
- compute the layers of the merkletree
- create proofs from the merkletree layers

I've also added a Merkletree class, which is initialized with a list of
hashes. This allows to compute multiple proofs for the same tree without
recomputing hashes all the time.

The merkleroot function still exists, but eventually it will be removed.

This is work-in-progress in order to resolve issue #202.

### CODE REVIEW

**Comment by hackaugusto** [comment]
sweet, really nice implementation, looking forward to merge it :)

**Comment by heikoheiko** [comment]
@schmir the initial implementation back then was optimized for speed. would be interesting to know how the readable version compares.

**Comment by schmir** [comment]
Thanks for the kind words.

I did run "python -m raiden.benchmark.merkle_tree_speed" and didn't notice any significant difference in speed.

My solution should be faster when creating multiple proofs for a single tree. I think I've seen code that would benefit from that (e.g. https://github.com/raiden-network/raiden/blob/master/raiden/channel.py#L237)

**Comment by schmir** [comment]
Here's the output of raiden.benchmark.merkle_tree_speed with current head vs my branch. There's not much difference.

```
(local) ~/raiden (git)-[master] % python -m raiden.benchmark.merkle_tree_speed
108979 additions per second
(local) ~/raiden (git)-[master] % python -m raiden.benchmark.merkle_tree_speed
112367 additions per second
(local) ~/raiden (git)-[master] % python -m raiden.benchmark.merkle_tree_speed
114008 additions per second
(local) ~/raiden (git)-[master] % python -m raiden.benchmark.merkle_tree_speed
110699 additions per second
(local) ~/raiden (git)-[master] % python -m raiden.benchmark.merkle_tree_speed
110922 additions per second
(local) ~/raiden (git)-[master] % git co issue-202-merkleproof 
Switched to branch 'issue-202-merkleproof'
Your branch is up-to-date with 'schmir/issue-202-merkleproof'.
(local) ~/raiden (git)-[issue-202-merkleproof] % python -m raiden.benchmark.merkle_tree_speed
113535 additions per second
(local) ~/raiden (git)-[issue-202-merkleproof] % python -m raiden.benchmark.merkle_tree_speed
114211 additions per second
(local) ~/raiden (git)-[issue-202-merkleproof] % python -m raiden.benchmark.merkle_tree_speed
115479 additions per second
(local) ~/raiden (git)-[issue-202-merkleproof] % python -m raiden.benchmark.merkle_tree_speed
115180 additions per second
(local) ~/raiden (git)-[issue-202-merkleproof] % python -m raiden.benchmark.merkle_tree_speed
115394 additions per second

```

**Pull request merged**
