### PR TITLE
adding dir for adrs and testing adr doc

### PR DESCRIPTION
**Pull request by czepluch**
We had a discussion of where to place ADRs. I think the best proposal was to have ADRs per project, so I'm not adding it for the main repo.

If we agree this is the right approach, I will also create a corresponding folder in the raiden-contracts and raiden-services.

I am adding the testing ADR as it is right now and a template we can follow.

### CODE REVIEW

**Comment by rakanalh** [comment]
I think this should be in `docs` to be generated and displayed on: [Read the docs](https://raiden-network.readthedocs.io/en/latest/)

**Comment by czepluch** [comment]
Good point. We can definitely do that and we have a nice display of them. Might have to change the template to be .rst though, but that's a minor details. If there are no objections I can change to that.

**Comment by LefterisJP** [comment]
@czepluch yes please put it with the rest of the docs

**Comment by czepluch** [comment]
Moved them to docs for now. Will update to .rst later and link them in RTD.

**Pull request merged**
