### PR TITLE
Use pickle instead of deepcopy (much faster!)

### PR DESCRIPTION
**Pull request by karlb**
This reduces the time to copy our state from 1.3s to something between
0.02s and 0.08s.

## PR review check list

Quality check list that cannot be automatically verified.

- Safety
    - [ ] The changes respect the necessary conditions for safety (https://raiden-network-specification.readthedocs.io/en/latest/smart_contracts.html#protocol-values-constraints)
-  Code quality
    - [ ] Error conditions are handled
    - [ ] Exceptions are propagated to the correct parent greenlet
    - [ ] Exceptions are correctly classified as recoverable or unrecoverable
- Compatibility
    - [ ] State changes are forward compatible
    - [ ] Transport messages are backwards and forward compatible
- Commits
    - [ ] Have good messages
    - [ ] Squashed unecessary commits
- If it's a bug fix:
    - Regression test for the bug
        - [ ] Properly covers the bug
        - [ ] If an integration test is used, it could not be written as a unit test
- Documentation
    - [ ] A new CLI flag was introduced, is there documentation that explains usage?
- Specs
    - [ ] If this is a protocol change, are the specs updated accordingly? If so, please link PR from the specs repo.
- Is it a user facing feature/bug fix?
    - [ ] Changelog entry has been added

### CODE REVIEW

**Comment by LefterisJP** [comment]
It does? Damn that's nice! I wonder why.

**Comment by karlb** [comment]
> It does? Damn that's nice! I wonder why.

One reason would be that's is written in C instead of python. But I assume there's more to it.

**Comment by Dominik2002** [comment]
here they say because cPickle doesn't copy that deep hehe https://stackoverflow.com/questions/1410615/copy-deepcopy-vs-pickle

**Comment by LefterisJP** [comment]
Intereresting link with explanations @Dominik1999 

Reading the accepted answer I kind of feel that we should then have tests to serialize/deserialize every state change/event class to make sure that we never break the assumptions that pickle makes.

**Pull request merged**
