### PR TITLE
Providing a partner address without a token address is not allowed

### LINKED ISSUE #2723: Wrong arguments in API function call
## Problem Definition

In the python API we call the function `list_channelstate_for_tokennetwork` twice with different parameters, where the third parameter should be the `token_address`.
https://github.com/raiden-network/raiden/blob/819dffa74ec813cc5bcd29b04a557814810b0e74/raiden/api/python.py#L559-L571

### PR DESCRIPTION
**Pull request by LefterisJP**
I don't catch it in the rest api since it's not even possible to do it there

Fix #2723

### CODE REVIEW

**Comment by palango** [comment]
Would be nice to add a test for this as well

**Comment by LefterisJP** [comment]
It's not possible to do this via the rest api. I can add one for python if you want.

**Comment by palango** [comment]
Yeah, just an assertion that the exception is thrown would be nice.

**Comment by LefterisJP** [comment]
@palango done

**Pull request merged**
