### PR TITLE
Use external ULID implementation instead of ours

### PR DESCRIPTION
**Pull request by karlb**
This one has a way to ensure monotonic ULIDs on systems with lower clock
resolution (e.g. Windows).

Includes the commit from https://github.com/raiden-network/raiden/pull/6665 to make the CI pass.

### CODE REVIEW

**Review by ulope — APPROVED** [review]
LGTM

**Comment by ahawker** [comment]
Hello. I'm the author of the [ulid](https://github.com/ahawker/ulid) package you're using here. Thanks!

Forgive me for coming across an old PR but the summary makes note of monotonic support, which it doesn't appear you're using. This potentially may be a bug (if you're expecting it) and I wanted to point you to the usage docs [here](https://github.com/ahawker/ulid#monotonic-support).

Even though the library has supported these methods for 5 months+, there was no usage example in the README to leverage them. My apologies for that.

Best,
Hawker

**Comment by karlb** [comment]
> Forgive me for coming across an old PR but the summary makes note of monotonic support, which it doesn't appear you're using. This potentially may be a bug (if you're expecting it) and I wanted to point you to the usage docs [here](https://github.com/ahawker/ulid#monotonic-support).

We need to create monotic ulids across restarts, this is why I explicitly create the provider to set the correct timestamp (even though the restart should take long enough to avoid ambiguity). I expect the code at
https://github.com/karlb/raiden/blob/3bb2f5ecac0599b97e1298eded39c449b185f82f/raiden/storage/sqlite.py#L332-L338
to correctly use the monotonic ulids. Is this not the case?

Thanks for your help, @ahawker!

**Comment by ahawker** [comment]
@karlb Yeah, that code looks correct, i'm not sure how I missed it in my original glance through the PR 😅 

I think `provider = ulid.providers.monotonic.Provider(ulid.providers.default.Provider())` and be simplified to `ulid.providers.MONOTONIC` https://github.com/ahawker/ulid/blob/master/ulid/providers/__init__.py#L13 but nbd.

**Pull request merged**
