### PR TITLE
stress test: unskipped it

### PR DESCRIPTION
**Pull request by hackaugusto**
[ci integration]

### CODE REVIEW

**Comment by hackaugusto** [comment]
Opened to check if the removal of coveralls improve the problem with the block gas limit

**Comment by LefterisJP** [comment]
First run it passed. Restarting only the stress test job.

**Comment by LefterisJP** [comment]
Passed 2nd time. Restarting again.

**Comment by LefterisJP** [comment]
Passed 5th time. Restarting one last time.

**Comment by LefterisJP** [comment]
Passed 6th time. Merging...

**Pull request merged**
