### PR TITLE
Upgrade raiden-contracts to fix the crash in production mode

### PR DESCRIPTION
**Pull request by pirapira**
This might work for https://github.com/raiden-network/raiden/issues/3723

### CODE REVIEW

**Comment by LefterisJP** [comment]
@pirapira can you squash the last two commits? You can do it after the tests pass with a [skip ci]

**Comment by pirapira** [comment]
@LefterisJP alright.

**Comment by pirapira** [comment]
```
raiden/tests/integration/test_echo_node.py::test_echo_node_response[matrix-False-120-15-channels_per_node0-1-4] Too long with no output (exceeded 10m0s)
```
https://circleci.com/gh/raiden-network/raiden/36216#tests/containers/9

Looks weird.

**Comment by LefterisJP** [comment]
@pirapira definitely not related to your PR. Can you restart the workflow only from failed?

**Comment by pirapira** [comment]
Squashed and force-pushed! (A lazy move).

**Comment by LefterisJP** [comment]
@pirapira no not lazy. The right move :+1:

**Comment by pirapira** [comment]
I fall back on restarting-everything.

**Pull request merged**
