### PR TITLE
Fix typing ChainMap -> ChannelMap

### PR DESCRIPTION
**Pull request by LefterisJP**

### CODE REVIEW

**Comment by rakanalh** [comment]
For the record, this should have failed on Python 3.7 but the version we are running on travis is 3.6 which means that 3.6 doesn't check for the validity / existence of the used argument type.

**Comment by andrevmatos** [comment]
But **there is** a `typing.ChainMap` member on upstream node, imported in top of our `typing` submodule. I think this may be some weird conflict bug I've seen before when using submodules with the same name as venv/stdlib modules

**Comment by hackaugusto** [comment]
Interesting, I didn't know there was a `ChainMap` in typing, but since we do  `from typing import *` and `ChainMap` is not in `__all__` we don't get this type in our `raiden.utils.typing` module

**Comment by rakanalh** [comment]
> But **there is** a `typing.ChainMap` member on upstream node, imported in top of our `typing` submodule. I think this may be some weird conflict bug I've seen before when using submodules with the same name as venv/stdlib modules

Just confirmed it exists in the upstream python typing module on 3.6.5

**Comment by LefterisJP** [comment]
Hey guys let's not waste any more time on this ;) 
We got important bugs to fix :)

**Pull request merged**
