### PR TITLE
Skip test_echo_node.py::test_event_transfer_received_success if not udp

### PR DESCRIPTION
**Pull request by andrevmatos**
This test was flaky with Matrix, couldn't reproduce locally, still looking for a proper solution.

### CODE REVIEW

**Comment by pcppcp** [comment]
can you post a link to Travis build to track the failures?

**Comment by pcppcp** [comment]
with tester, I got this error

```
>       assert must_contain_entry(
            events,
            EventTransferReceivedSuccess,
            {'amount': 1, 'initiator': app0.raiden.address},
        )
E       AssertionError: assert None
E        +  where None = must_contain_entry([<SendSecretRequest msgid:1538373142268889217 paymentid:626979735788006538 amount:3 secrethash:a7e03b51 recipient:28c2...a7e03b51 recipient:28c26be1>, <SendRevealSecret msgid:2265224035672675528 secrethash:a7e03b51 recipient:28c26be1>, ...], EventTransferReceivedSuccess, {'amount': 1, 'initiator': b'\xc9\x9f4z\xa4H^cZwU\xcd\xc7\xc4\xfc\x89;\xb1\xf0\xcf'})
```

**Comment by andrevmatos** [comment]
https://travis-ci.org/raiden-network/raiden/jobs/398997039#L1023

**Comment by pcppcp** [comment]
yeah, good ol' boy `raiden_chain` wait. It's like ghost hunting with this one.

**Comment by LefterisJP** [comment]
This is not the only test unfortunately, but yes this definitely is flaky with matrix.

**Pull request merged**
