### PR TITLE
CONTRIBUTING.md: encourage list/dict literals rather than constructors

### PR DESCRIPTION
**Pull request by istankovic**

### CODE REVIEW

**Review by ulope — APPROVED** [review]
👍 👍

**Comment by palango** [comment]
@istankovic There's even a lint for this, which is currently ignored and should be removed then: https://github.com/adamchainz/flake8-comprehensions#c408-unnecessary-dictlisttuple-call---rewrite-as-a-literal

**Comment by istankovic** [comment]
> @istankovic There's even a lint for this, which is currently ignored and should be removed then: https://github.com/adamchainz/flake8-comprehensions#c408-unnecessary-dictlisttuple-call---rewrite-as-a-literal

Eh, it seems the lint catches non-empty constructions too, e.g.
```python
                data = dict(                                                                                                                                                                  
                    channel_balance=channel_balance,                                                                                                                                          
                    min_balance=MIN_MONITORING_AMOUNT_DAI,                                                                                                                                    
                    channel_id=channel_state.canonical_identifier.channel_identifier,                                                                                                         
                    token_address=to_checksum_address(DAI_TOKEN_ADDRESS),                                                                                                                     
                )                                                                                                                                                                             
```

And we have quite a few of those. Do we want to change those as well?

**Comment by ulope** [comment]
Hm I wouldn't want to enforce that.
Non-empty dict constructors are sometimes easier to type / read than literals.

**Comment by istankovic** [comment]
> Hm I wouldn't want to enforce that.
> Non-empty dict constructors are sometimes easier to type / read than literals.

Exactly my feeling. It would be nice to just have a lint for the empty case.
I'm going to change the empty instances only.

**Pull request merged**
