### PR TITLE
Replaced secp256k1 with coincurve

### PR DESCRIPTION
**Pull request by hrishikeshio**
Solves #513 
Special thanks to @ofek for writing coincurve and for help.

### CODE REVIEW

**Comment by ofek** [comment]
You can completely remove anything to do with contexts. As coincurve uses a global context by default, you don't need to create one yourself unless you're doing multiprocessing. Also note that all contexts are thread-safe.

**Comment by hrishikeshio** [comment]
@coredevs please advice if I should remove context or not. The tests run in parallel, so they wont be  using same context unless explicitly specified, right?
I personally prefer explicit approach.
@czepluch

**Comment by czepluch** [comment]
Didn't it work fine with `GLOBAL_CTX` before? Then I think we should just stick with what we did before.

**Comment by ofek** [comment]
@czepluch The thing is, coincurve already does that. You don't need to use a context yourself.

**Comment by LefterisJP** [comment]
@hrishikeshio Can you remove the global context and rebase so that we can merge the PR?

**Comment by hrishikeshio** [comment]
@LefterisJP Ok will do.

**Comment by hrishikeshio** [comment]
@LefterisJP rebased. Ready to merge.

**Comment by ofek** [comment]
@hrishikeshio Another rebase is required unfortunately. Also, please change minimum version to 4.5.1 to include FreeBSD support and https://github.com/ofek/coincurve/commit/6da9164c88938eecc89d7e5a1dd73646b23e6bf3

@LefterisJP @czepluch Are you prepared to merge after final rebase?

**Comment by LefterisJP** [comment]
@ofek Thank you for the heads up regarding 4.5.1, rebased and added the version change.

**Pull request merged**
