### PR TITLE
Update pyinstaller scripts after pyethereum removal

### LINKED ISSUE #1469: Update pyinstaller packaging
## Problem Definition

After the removal of the `pyethereum` dependency we need to update the pyinstaller scripts.

### PR DESCRIPTION
**Pull request by palango**
Fixes #1469

This updates the pyinstaller script but currently the package fails with
```
Traceback (most recent call last):
  File "build/raiden/raiden-script.py", line 2, in <module>
    raiden.__main__.main()
  File "raiden/__main__.py", line 5, in main
    import gevent.monkey
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "gevent/__init__.py", line 87, in <module>
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "gevent/_hub_local.py", line 101, in <module>
  File "gevent/_util.py", line 105, in import_c_accel
  File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'gevent.__hub_local'
[16241] Failed to execute script raiden-script
```

### CODE REVIEW

**Comment by palango** [comment]
@ulope Whenever you find some time please have a look. It's not urgent however.

**Comment by ulope** [comment]
@palango Ok will do, I should have some time over the weekend.

**Comment by palango** [comment]
Thanks, now it starts :)

But then it complains about the hashing provider, so it seems it doesn't find the installation of `pycryptodome`.
```
./dist/raiden-0.3.1.dev429+g6ae3fc37.d20180531-macos --keystore-path ~/Library/Ethereum/testnet/keystore --address=df173a5173c3d0ae5ba11dae84470c5d3f112345 --password-file pw.txt --nat=ext:123.34.45.78 --transport matrix
Welcome to Raiden, version 0.3.1.dev429+g6ae3fc37.d20180531!
WARNING: The Matrix transport is experimental
Traceback (most recent call last):
  File "build/raiden/raiden-script.py", line 2, in <module>
    raiden.__main__.main()
  File "raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "click/core.py", line 722, in __call__
  File "click/core.py", line 697, in main
  File "click/core.py", line 1043, in invoke
  File "click/core.py", line 895, in invoke
  File "click/core.py", line 535, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 813, in run
    app_ = _run_app()
  File "raiden/ui/cli.py", line 737, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "click/core.py", line 535, in invoke
  File "raiden/ui/cli.py", line 514, in app
    address_hex, privatekey_bin = prompt_account(address_hex, keystore_path, password_file)
  File "raiden/ui/cli.py", line 680, in prompt_account
    privatekey_bin = accmgr.get_privkey(address_hex, password)
  File "raiden/accounts.py", line 154, in get_privkey
    acc = Account(data, password, self.accounts[address])
  File "raiden/accounts.py", line 183, in __init__
    self.unlock(password)
  File "raiden/accounts.py", line 232, in unlock
    self._privkey = decode_keyfile_json(self.keystore, password.encode('UTF-8'))
  File "eth_keyfile/keyfile.py", line 49, in decode_keyfile_json
  File "eth_keyfile/keyfile.py", line 165, in _decode_keyfile_json_v3
  File "eth_utils/crypto.py", line 9, in keccak
  File "eth_hash/main.py", line 38, in __call__
  File "eth_hash/main.py", line 22, in _hasher_first_run
  File "eth_hash/backends/auto.py", line 18, in keccak256
  File "eth_hash/backends/auto.py", line 11, in _initialize
  File "eth_hash/utils.py", line 15, in auto_choose_backend
  File "eth_hash/utils.py", line 52, in choose_available_backend
ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
Install with `pip install eth-hash[pycryptodome]`.
[36874] Failed to execute script raiden-script
```

**Comment by ulope** [comment]
Sigh...
Ok, I'll have another look :)

**Comment by ulope** [comment]
Now it should work :)

**Comment by palango** [comment]
I rebased and fixed the merge conflict, but now I get the following error:

```
./dist/raiden-0.3.1.dev491+gdc740a69-macos --keystore-path ~/Library/Ethereum/testnet/keystore --nat=ext:123.34.45.78 --transport matrix --no-sync-check
Traceback (most recent call last):
  File "build/raiden/raiden-script.py", line 2, in <module>
    raiden.__main__.main()
  File "raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden/ui/cli.py", line 30, in <module>
    from raiden.api.rest import APIServer, RestAPI
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden/api/rest.py", line 62, in <module>
    from raiden.raiden_service import (
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden/raiden_service.py", line 15, in <module>
    from raiden.network.blockchain_service import BlockChainService
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden/network/blockchain_service.py", line 14, in <module>
    from raiden.network.proxies import (
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden/network/proxies/__init__.py", line 2, in <module>
    from raiden.network.proxies.channel_manager import ChannelManager  # NOQA
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden/network/proxies/channel_manager.py", line 15, in <module>
    from raiden.blockchain.abi import (
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden/blockchain/abi.py", line 19, in <module>
    from raiden_contracts.contract_manager import ContractManager
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "raiden_contracts/contract_manager.py", line 127, in <module>
  File "raiden_contracts/contract_manager.py", line 42, in __init__
  File "raiden_contracts/contract_manager.py", line 97, in precompile_contracts
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/gz/0f_3f9k96gd1hblwgd1r8h280000gn/T/_MEIgS4bYc/raiden_contracts/contracts'
[77311] Failed to execute script raiden-script
```

**Pull request merged**
