### PR TITLE
Updates WebUI to v0.10.1

### PR DESCRIPTION
**Pull request by manuelwedler**
## PR review check list

Quality check list that cannot be automatically verified.

- Safety
    - [ ] The changes respect the necessary conditions for safety (https://raiden-network-specification.readthedocs.io/en/latest/smart_contracts.html#protocol-values-constraints)
-  Code quality
    - [ ] Error conditions are handled
    - [ ] Exceptions are propagated to the correct parent greenlet
    - [ ] Exceptions are correctly classified as recoverable or unrecoverable
- Compatibility
    - [ ] State changes are forward compatible
    - [ ] Transport messages are backwards and forward compatible
- Commits
    - [ ] Have good messages
    - [ ] Squashed unecessary commits
- If it's a bug fix:
    - Regression test for the bug
        - [ ] Properly covers the bug
        - [ ] If an integration test is used, it could not be written as a unit test
- Documentation
    - [ ] A new CLI flag was introduced, is there documentation that explains usage?
- Specs
    - [ ] If this is a protocol change, are the specs updated accordingly? If so, please link PR from the specs repo.
- Is it a user facing feature/bug fix?
    - [ ] Changelog entry has been added

### CODE REVIEW

**Comment by LefterisJP** [comment]
Looks good to me in principle but just wanna check with @dominik and @rakanalh regarding the code freeze for Alderaan. That does not affect webui, right?

**Comment by rakanalh** [comment]
@manuelwedler What is changed in this webui release?

**Comment by LefterisJP** [comment]
@rakanalh you can see in the changelog: https://github.com/raiden-network/webui/releases/tag/v0.10.1

**Comment by rakanalh** [comment]
Ok sounds like minor changes. We can merge the changes IMO

**Comment by LefterisJP** [comment]
I also think so. @Dominik1999 ?

**Comment by manuelwedler** [comment]
@rakanalh Yes, these are just minor changes. Basically bug fixes and improvements to the notification panel.

**Comment by rakanalh** [comment]
Checked with Dominik, he is also ok with merging this. So merging.

**Pull request merged**
