### PR TITLE
Bump version to 3.0.0

### LINKED ISSUE #7351: Release 3.0.0
## Abstract

TODO:
- [ ] store CI build logs for documentation (ask @karlb for details)

### PR DESCRIPTION
**Pull request by palango**
## Description

Fixes: https://github.com/raiden-network/raiden/issues/7351

### CODE REVIEW

**Comment by ulope** [comment]
This still needs a new known servers list.

**Comment by palango** [comment]
> This still needs a new known servers list.

Aren't those correct? https://github.com/raiden-network/raiden/blob/develop/raiden/settings.py#L45

**Comment by ulope** [comment]
Ah you're right, sorry. 
I forgot we already created that one.

**Comment by palango** [comment]
Now I'm actually unsure if the development one should be updated!?

**Comment by ulope** [comment]
Since it has the same content as the old one it should be fine.

**Review by ulope — APPROVED** [review]
🎉

**Pull request merged**
