### PR TITLE
Added raiden api client tests

### PR DESCRIPTION
**Pull request by eorituz**
## Description

Please, describe what this PR does in detail:
- Added tests for raiden api client. The api client wraps the raiden api, simplifying the usage of raiden for demos and applications build in python

### CODE REVIEW

**Review by karlb — APPROVED** [review]
Looks good!

**Comment by karlb** [comment]
Running `make black` should fix the linting error. Use `make lint` locally to catch this before pushing.

**Comment by ulope** [comment]
The `raiden-api-client` package needs to be added to the dev requirements.

**Comment by eorituz** [comment]
Fixed the linting issue and added the raiden-api-client to the requirements.
Note: compiling the new requirements also removed 'appnope==0.1.0' which shouldn't be in there anyways according to @ulope

**Pull request merged**
