### PR TITLE
Add bundling and artifact upload to travis

### PR DESCRIPTION
**Pull request by konradkonrad**
This will build the AppImage on tagged commits and upload it to the corresponding github release page.

**Note**: not tested, github upload _only_ works on tags. I would like to do a pre-release tag after this is merged.

### CODE REVIEW

**Comment by LefterisJP** [comment]
Can you please revert the indentation back in the travis yaml file? Other than that I guess it's fine.

**Comment by konradkonrad** [comment]
@LefterisJP that's the formatting the [`travis` cli tool}(https://github.com/travis-ci/travis.rb#readme) applies, which I'd find helpful to keep.

**Comment by LefterisJP** [comment]
@konradkonrad Sure then that makes sense and you can disregard my comment.

**Comment by LefterisJP** [comment]
Looks fine to me then. Will approve and please don't forget to run a test with a "pre-release/test" tag once merged.

**Comment by konradkonrad** [comment]
>  please don't forget to run a test with a "pre-release/test" tag once merged.

sure, I'm looking forward to it :)

**Comment by ulope** [comment]
This still has two small issues:
- The `make bundle` command is now being run every time. Easiest solution would probably be to check for existance of the `TRAVIS_TAG` env variable
- The `before_install` and `install` steps are still being run for the `deploy` stage since they are inherited.

**Comment by konradkonrad** [comment]
> The before_install and install steps are still being run for the deploy stage since they are inherited.

I guess that's good, because it allows to do the pypi deployment, too

> The make bundle command is now being run every time.

Hmm, yeah. I guess if we manage to cache the docker build, that would be a good thing, because we would see errors with the bundler early on...?

**Comment by ulope** [comment]
> I guess that's good, because it allows to do the pypi deployment, too
Godo point. 

> Hmm, yeah. I guess if we manage to cache the docker build, that would be a good thing, because we would see errors with the bundler early on...?

That would be optimal. As it is now the bundling is adding ~15 minutes to the runtime. We should probably wait with this until after the dev preview.

**Pull request merged**
