### PR TITLE
Try parallel tests with xdist

### PR DESCRIPTION
**Pull request by karlb**
Yet another try to get parallel test running reliably.

### CODE REVIEW

**Comment by rakanalh** [comment]
@karlb do you want to continue/finish this at some point or should we close the PR?

**Comment by karlb** [comment]
The changes here make sense and I would like to merge them at some time not too far into the future. Since all flakyness issues seemed to be even more problematic in this setup I wanted to wait for the flakiness to be reduced before investigating this, again. During the last try all parity tests succeeded and only two geth tests failed. So merging this soon seems to be achievable.

Benefits would be greatly reduced CircleCI costs and quicker CI results.

**Comment by karlb** [comment]
The tests seem to run fine, now. But the coverage does not work as expected, yet. It probably makes sense to merge https://github.com/raiden-network/raiden/pull/4547 first before changing the coverage handling, here.

**Comment by Dominik1999** [comment]
Can you try to close or push this PR forward until 20 of Feb? Would also be sufficient to have a plan what to do with it

**Comment by karlb** [comment]
TODOs:
- [ ] Reduce flakiness in the develop branch. Otherwise we don't know if flakiness is caused by xdist
- [ ] Make sure the port generator is not flaky (https://github.com/raiden-network/raiden/pull/5908)
- [ ] Figure out why some geth nodes suddenly die (e.g. in https://app.circleci.com/jobs/github/raiden-network/raiden/111488/tests). See also https://discuss.circleci.com/t/running-dmesg-debugging-oom/34535.

**Pull request closed without merging**
