### PR TITLE
Use TokenNetworkAddress consistently

### PR DESCRIPTION
**Pull request by palango**
At some point during the mypy addition we decided to use a
Union[TokenNetworkAddress, TokenNetworkID] to make the PR easier.
The time has come to change that and not handle these Union any more.

Edit:
I also changed the PaymentNetworkID now.

⚠️ I guess this requires changes to the webUI and the scenario player.

### CODE REVIEW

**Comment by rakanalh** [comment]
I am under the impression that we wanted to use `TokenNetworkAddress` instead of `TokenNetworkID`.

**Comment by palango** [comment]
> I am under the impression that we wanted to use `TokenNetworkAddress` instead of `TokenNetworkID`.

I don't car TBH, I just saw `ChainID`  and `ChannelID` in the `CanonicalIdentifier`, so I chose that, but I can rename.

**Comment by palango** [comment]
Ok, so with the renaming this became bigger than I expected.

I'd still argue that the renaming makes sense and now is a good point in time to do this, but this also changes the API.

**Comment by konradkonrad** [comment]
I like this.
For our existing API consumers, we could think about adding a deprecated (and `warning` issue-ing) alias in request bodies.

**Pull request merged**
