### PR TITLE
Bump contracts requirement to 0.29.1

### PR DESCRIPTION
**Pull request by LefterisJP**
## Description

Fixes: #4583 

No mypy errors occurred, at least locally.

## PR review check list

Quality check list that cannot be automatically verified.

- [ ] Safety
    - [ ] The changes respect the necessary conditions for safety (https://raiden-network-specification.readthedocs.io/en/latest/smart_contracts.html#protocol-values-constraints)
- [ ] Code quality
    - [ ] Error conditions are handled
    - [ ] Exceptions are propagated to the correct parent greenlet
    - [ ] Exceptions are correctly classified as recoverable or unrecoverable
- [ ] Compatibility
    - [ ] State changes are forward compatible
    - [ ] Transport messages are backwards and forward compatible
- [ ] Regression test for the bug
    - [ ] Properly covers the bug
    - [ ] If an integration test is used, it could not be written as a unit test
- [ ] Commits
    - [ ] Have good messages
    - [ ] Squashed unecessary commits

### CODE REVIEW

**Comment by palango** [comment]
So I guess this will need a few more updates: https://web3py.readthedocs.io/en/stable/v5_migration.html

**Comment by LefterisJP** [comment]
@palango yep. For some reason tests did not fail locally for me. Something with my venv :). On it.

**Comment by LefterisJP** [comment]
Hmm but @palango @pirapira this will also need contract code changes.

Just starting to run unit tests locally in a fixed venv shows me that contracts python code uses a private module from web3, called `_utils` which no longer exists.

```
ImportError while loading conftest '/home/lefteris/ew/raiden/raiden/tests/conftest.py'.
raiden/tests/conftest.py:34: in <module>
    from raiden.constants import (
raiden/constants.py:6: in <module>
    from raiden.utils.secrethash import sha256_secrethash
raiden/utils/__init__.py:26: in <module>
    from raiden.utils.typing import (
raiden/utils/typing.py:6: in <module>
    from raiden_contracts.contract_manager import CompiledContract  # NOQA pylint:disable=unused-import
../../.virtualenvs/raiden/lib/python3.7/site-packages/raiden_contracts/contract_manager.py:11: in <module>
    from raiden_contracts.constants import ID_TO_NETWORKNAME, DeploymentModule
../../.virtualenvs/raiden/lib/python3.7/site-packages/raiden_contracts/constants.py:8: in <module>
    from raiden_contracts.utils.type_aliases import ChainID
../../.virtualenvs/raiden/lib/python3.7/site-packages/raiden_contracts/utils/__init__.py:4: in <module>
    from .logs import *
../../.virtualenvs/raiden/lib/python3.7/site-packages/raiden_contracts/utils/logs.py:9: in <module>
    from web3._utils.events import get_event_data
E   ModuleNotFoundError: No module named 'web3._utils'
```

**Comment by pirapira** [comment]
All changes between 0.29.0 and 0.29.1 will be reverted.

**Pull request closed without merging**
