### PR TITLE
Mention debug file in issue template

### PR DESCRIPTION
**Pull request by palango**

### CODE REVIEW

**Comment by LefterisJP** [comment]
Ah good idea. At least for now we have it on by default. Is it user configurable, or not yet? If it is can we also mention how to activate it (for the future when we won't have it on by default).

**Comment by palango** [comment]
> At least for now we have it on by default. Is it user configurable, or not yet?

It's on my default and is not user configurable atm. What would you like to be configurable? You can still use `--log-file` which uses the custom filter settings.

**Comment by LefterisJP** [comment]
@palango Yep that's what I meant. It is user configurable then via the `--log-file` argument. If a user provides the `--log-file`  does it not overwrite the hardcoded `raiden-debug.log`? If it doesn't, it should.

**Comment by palango** [comment]
Currently debug output is always written to `raiden-debug.log`, even if you specify logging to a different file via the `--log-file` argument.

**Comment by LefterisJP** [comment]
Okay then I will make an issue to change that. We should have it on by default but I don't see why we would not allow the user to change this behaviour.

**Comment by ulope** [comment]
The idea was to have an always-on log that was reliably there independent of user (mis-)configuration. If we were to make it user-configurable it would IMO slightly defeat the purpose.

**Comment by LefterisJP** [comment]
@ulope I disagree. And as far as i can see from the issue what I expected to be done is what @hackaugusto [mentioned](https://github.com/raiden-network/raiden/issues/1844#issuecomment-405578861) in this comment. A default debug `--log-file`.

User misconfiguration imo falls in the same area as user deleting the logfile. Not our problem. But not allowing the user to disable debug logging for whatever reason is our problem. Anyway this is not the place to discuss this issue.

I will merge the PR as for latest master the addition to the issue template is indeed correct.

**Pull request merged**
