### PR TITLE
travis: enable geth logging

### PR DESCRIPTION
**Pull request by hackaugusto**
making the test suite more verbose

### CODE REVIEW

**Comment by LefterisJP** [comment]
Is there a reason for this? We had removed this because it hits the travis limit and then we can no longer see test output. Even if you click the full log link it goes over their file limit.

**Comment by hackaugusto** [comment]
Not enough logging for figuring out the polling timeouts
https://travis-ci.org/raiden-network/raiden/jobs/176037543#L458-L475
https://travis-ci.org/raiden-network/raiden/jobs/176040816#L905-L918

**Comment by LefterisJP** [comment]
But .. needs a rebase!

**Comment by LefterisJP** [comment]
Seems to have worked, for errors only including folding of all failed builds stdout and stderr as we discussed.

2016-11-16-014940_883x216_scrot

**Pull request merged**
