### PR TITLE
Remove direct transfers from the codebase

### LINKED ISSUE #3097: Remove DirectTransfer message from the implementation
@LefterisJP [says](https://github.com/raiden-network/spec/pull/137#issuecomment-442826348) DirectTransfer messages are never used, so they should be removed.  He also has a git branch somewhere that does this.

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix #3097

### CODE REVIEW

**Comment by LefterisJP** [comment]
Need to fix at least 1 failing test. Will work on it.

**Comment by rakanalh** [comment]
Reviewing this

**Comment by LefterisJP** [comment]
Thanks @rakanalh. Will only merge after the binaries for the workshop are generated.

**Comment by LefterisJP** [comment]
Okay so now all is green. I occasionally also got the Access Token problem but that is tracked by https://github.com/raiden-network/raiden/issues/3130.

So to make it all green had to adjust some tests that were failing almost exclusively on Circle CI. They were due to timing issues inside the tests themselves. It seems that CircleCI is really fast which also can uncover timing problems.

The timing problem was that sometimes in the tests where we stop the target to make a transfer hang, `mediated_transfer_async()` may run very fast and finish before the target's app is stopped.

So I added some [mock contexts](https://github.com/raiden-network/raiden/pull/3125/commits/141489c0df635694180df76a351a96b010afdef8#diff-703320893a636e44af374c3dd079ecd8R37) in 2 of the tests that make sure that either the protocol never completes or that we never mark target as offline. This way the timing issues were eliminated.

**Pull request merged**
