### PR TITLE
added utility methods to convert messages

### PR DESCRIPTION
**Pull request by hackaugusto**
these methods will be used on the event handler.

### CODE REVIEW

**Comment by palango** [comment]
Looks good, but shouldn't every function check the if the event type of the argument matches the message?

**Comment by hackaugusto** [comment]
> but shouldn't every function check the if the event type of the argument matches the message?

Humm, I have nothing against/in-favor of this approach. Right now this would introduce an import cicle, maybe we should move it to free-standing functions

**Comment by palango** [comment]
> I think ideally we would either stick to static type checking or use the duck type nature of the language (IOW, avoid isinstance checks)

I agree. I think here type annotations are useful as documentation as well.

**Comment by LefterisJP** [comment]
Also looks good to me. And +1 on the duck typing + type annotations.

**Pull request merged**
