### PR TITLE
Fix startup for private networks

### LINKED ISSUE #3687: Startup crash with private chain
Using a private chain (ID 4321) and starting raiden (master) I get the flow crash:

```
/Users/admin/.virtualenvs/raiden/bin/python -m raiden --datadir exchange-a --keystore-path /Users/admin/xud-eth/blkchain1/keystore/ --network-id 4321 --accept-disclaimer --address 0x4F6799E2341379eA52213919622B9bEc80a1b655 --rpc --api-address 0.0.0.0:5001 --web-ui --environment-type development --password-file passwd_file --console --no-sync-check --accept-disclaimer --tokennetwork-registry-contract-address 0xaa1c9586BbCF5795828A09d705d41B7fF65dD90A --secret-registry-contract-address 0x6DC70232E11b5b5C4A5f2DEbe7DfE83752b24de9 --endpoint-registry-contract-address 0x147fa2035beB2a5e6613b232213e6962B6bD1C47 --gas-price 10000000000
Welcome to Raiden, version 0.100.2rc5.dev548+g50e6f3ff.d20190325!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released as a test version under an MIT license and may contain    |
| errors and/or bugs. No guarantee or representations whatsoever is  |
| made regarding its suitability (or its use) for any purpose or     |
| regarding its compliance with any applicable laws and regulations. |
| Use of the software is at your own risk and discretion and by      |
| using the software you acknowledge that you have read this         |
| disclaimer, understand its contents, assume all risk related       |
| thereto and hereby release, waive, discharge and covenant not to   |
| sue Brainbot Labs Establishment or any officers, employees or      |
| affiliates from and for any direct or indirect liability resulting |
| from the use of the software as permissible by applicable laws and |
| regulations.                                                       |
|                                                                    |
| Privacy Warning: Please be aware, that by using the Raiden Client, |
| among others, your Ethereum address, channels, channel deposits,   |
| settlements and the Ethereum address of your channel counterparty  |
| will be stored on the Ethereum chain, i.e. on servers of Ethereum  |
| node operators and ergo are to a certain extent publicly available.|
| The same might also be stored on systems of parties running Raiden |
| nodes connected to the same token network. Data present in the     |
| Ethereum chain is very unlikely to be able to be changed, removed  |
| or deleted from the public arena.                                  |
|                                                                    |
| Also be aware, that data on individual Raiden token transfers will |
| be made available via the Matrix protocol to the recipient,        |
| intermediating nodes of a specific transfer as well as to the      |
| Matrix server operators.                                           |
----------------------------------------------------------------------
2019-03-26 16:20:55.398350 [info     ] Starting Raiden                [raiden.ui.runners] architecture=x86_64 distribution=source python_implementation=CPython python_version=3.7.2 raiden=0.100.2rc5.dev548+g50e6f3ff.d20190325 system=macOS 10.14 64bit
Raiden is running in development mode
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/Users/admin/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/raiden/raiden/ui/cli.py", line 494, in run
    app = runner.run()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/admin/raiden/raiden/ui/app.py", line 405, in run_app
    ID_TO_NETWORKNAME[node_network_id] != 'smoketest'
KeyError: 4321
```

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix #3687

We really need tests for all possible argument values in the startup ...

### CODE REVIEW

**Comment by offerm** [comment]
@LefterisJP This fix exposes the next problem:

```
Raiden is running in development mode
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/Users/admin/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/raiden/raiden/ui/cli.py", line 494, in run
    app = runner.run()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/admin/raiden/raiden/ui/app.py", line 412, in run_app
    services_contracts[CONTRACT_USER_DEPOSIT]['address'],
KeyError: 'UserDeposit'
```

**Comment by LefterisJP** [comment]
@offerm So you are running in development mode. I guess you have not deployed the new services contracts, right? You probably don't need them right now but this is a bit untested territory. Can you try my new pushed commits?

**Comment by LefterisJP** [comment]
@offerm  ping ^ ?

**Comment by offerm** [comment]
@LefterisJP I'm running in development mode and did deploy the service contracts. 

The reason that I'm not using the `production` contracts is that my deployed token is not being shown with vi\tokens api. Would  you like me to open an issue for it?

Will try to test your branch shortly

**Comment by offerm** [comment]
@LefterisJP Much better. Most problems resolved.

Only thing I spotted with your branch (and raiden's master too) is that after making a payment from A to B and restarting B, you get this:

```

You are connected to the '4321' network and the DB path is: /Users/admin/xud-eth/exchange-b/node_133499f5/netid_4321/network_aa1c9586/v20_log.db
2019-03-28 13:56:30.236256 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix.utils] sorted_servers=['https://transport03.raiden.network', 'https://transport01.raiden.network', 'https://transport02.raiden.network']
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/Users/admin/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/raiden/raiden/ui/cli.py", line 494, in run
    app = runner.run()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/admin/raiden/raiden/ui/app.py", line 521, in run_app
    raiden_app.start()
  File "/Users/admin/raiden/raiden/app.py", line 152, in start
    self.raiden.start()
  File "/Users/admin/raiden/raiden/raiden_service.py", line 526, in start
    self._initialize_monitoring_services_queue(chain_state)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 958, in _initialize_monitoring_services_queue
    update_services_from_balance_proof(self, chain_state, balance_proof)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 219, in update_services_from_balance_proof
    update_path_finding_service_from_balance_proof(raiden, chain_state, new_balance_proof)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 245, in update_path_finding_service_from_balance_proof
    raiden.transport.send_global(constants.PATH_FINDING_BROADCASTING_ROOM, msg)
  File "/Users/admin/raiden/raiden/network/transport/matrix/transport.py", line 554, in send_global
    room_name = make_room_alias(self.network_id, room)
  File "/Users/admin/raiden/raiden/utils/runnable.py", line 80, in __getattribute__
    return super().__getattribute__(name)
  File "/Users/admin/raiden/raiden/network/transport/matrix/transport.py", line 606, in network_id
    assert self._raiden_service is not None
AssertionError
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x10c862ae8>
Traceback (most recent call last):
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 333, in __del__
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 320, in release
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 72, in emit
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 958, in handleError
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 104, in print_exception
  File "/Users/admin/raiden/raiden/log_config.py", line 145, in tracebackexception_format
  File "/Users/admin/raiden/raiden/log_config.py", line 126, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down

Process finished with exit code 1
```

**Comment by pirapira** [comment]
I was able to reproduce the issue #3687, and I don't see the problem after switching to this PR.

**Comment by pirapira** [comment]
The newer problems @offerm is seeing is about contract deployments, so recent `raiden-contract` upgrades might have already solved it.

**Comment by pirapira** [comment]
This PR fixes the startup.  That's an improvement.  Let's merge it.  Then everybody will be on the same page regarding to the next issue.

**Comment by LefterisJP** [comment]
@pirapira Sure, I agree. Let's do so. I/We can react pretty fast to people testing private chain deployments.

**Pull request merged**
