### PR TITLE
standardized code to single quotes

### PR DESCRIPTION
**Pull request by hackaugusto**
Changed most strings to the single quote style

### CODE REVIEW

**Comment by palango** [comment]
Can we enforce this automatically? A quick search brought up https://github.com/zheller/flake8-quotes

**Comment by hackaugusto** [comment]
@palango Sure, could you open a PR with that tool setup? Also, this one needs a review :)

**Comment by palango** [comment]
This looks fine. Before I approve: Is using single quotes consensus in the raiden team?

**Comment by hackaugusto** [comment]
Refer to [`Usage of single and double quotes`](https://github.com/raiden-network/raiden/blob/master/CONTRIBUTING.md#python).

**Pull request merged**
