### PR TITLE
Mypy fixes for `raiden/network/transport`

### PR DESCRIPTION
**Pull request by konradkonrad**
Part of #3798

```
# Before
mypy --ignore-missing-imports raiden/network/transport|grep -v raiden.tests|wc -l
15
# After
mypy --ignore-missing-imports raiden/network/transport|grep -v raiden.tests|wc -l
0
```

## Notes for reviewer:
Please especially check the sanity of the commits:
- `Silence mypy`

### CODE REVIEW

**Comment by konradkonrad** [comment]
I reverted the change for `Runnable.start` and instead chose to silence the error.

**Comment by palango** [comment]
When the whole `raiden/transport` module checks without errors, I'd also add it to the mypy target in `Makefile`.

**Comment by ulope** [comment]
@konradkonrad Ah right, the signature mismatch. Does it pacify mypy if we change base method to `.start(self, *args, **kwargs)`?

**Comment by konradkonrad** [comment]
> @konradkonrad Ah right, the signature mismatch. Does it pacify mypy if we change base method to `.start(self, *args, **kwargs)`?

no, it doesn't :(

**Pull request merged**
