### PR TITLE
Scenario assertion

### LINKED ISSUE #2579: Add an error assert task to the scenario player.
The he scenario player currently does not allow to test that something fails as expected, i.e. opening a channel twice.

### PR DESCRIPTION
**Pull request by err508**
Adds a `RaiseTask` group to the scenario player tasks, s.t. it can be testet that some API calls raise an error (i.e. depositing the same amount twice, opening a channel twice). 

Closes #2579

### CODE REVIEW

**Comment by rakanalh** [comment]
@err508 do you mind rebasing your branch on the latest master?

**Comment by ulope** [comment]
I think if we want to go with this it'd be more useful to have a task that wraps a single other one. Not a SerialTask that ignores all exceptions.

I.e. something like this:
```
tasks:
    - ignore_exception:
        exceptions: ['KeyError', 'RuntimeError']
        task:
            open_channel: {...}
```

**Comment by rakanalh** [comment]
@ulope since we're dealing with APIs, i don't think the example is valid. What Tobi is trying to do here is also something that i want to have is to be able to check status codes and/or error messages. 
What Tobi implemented is a new task that:
1. Repeats execution for a pre-determined number of times
2. Catches exceptions
But in this case, we're not interested in exceptions raised by the scenario players but rather, failures in the requests that have been made.

**Comment by err508** [comment]
@ulope 

> Not a SerialTask that ignores all exceptions.

With  `except RESTAPIError` it can be only one of the three cases [here](/home/no_name/raiden/tools), no? If so potential false negatives are limited to `RequestException, ValueError, UnicodeDecodeError` exceptions. Instead of raising `RESTAPIError`, we could propagate the `resp.status_codes` here to get rid of  these three. 

>  it'd be more useful to have a task that wraps a single other one. 

I'd be prefer to have a simple task group to assert failure of tasks in batch, maybe I misunderstood `ignore_exception`, but my idea here was to `test for failure`, not to ignore it.

**Comment by ulope** [comment]
@rakanalh:
> Repeats execution for a pre-determined number of times

Both `SerialTask` and `ParallelTask` already can do that

> But in this case, we're not interested in exceptions raised by the scenario players but rather, failures in the requests that have been made.

Exactly. That's why I'm saying that this exception based approach is not the best solution.

@err508:
`RESTAPIError` can also be the result of various other failures (e.g. connection refused, timeout (once that is fixed), connection reset by peer) which can happen for example if a node crashes etc.

So, let me make another proposal:
Let's change this so the `Serial` and `Parallel` tasks gain two optional parameters:
- `ignore_exceptions`: A list of exceptions that are ignored when raised by the sub-tasks
- `require_exceptions`. A list of exceptions, one of which must *must* be raised by every sub-task.

Does that make sense?

Additionally I've implemented the http status code matching: raiden-network/raiden#2599 so we can use whichever fits better for a specific scenario.

**Comment by err508** [comment]
was extended via #2599

**Pull request closed without merging**
