### PR TITLE
Add note on Infura and WebUI

### PR DESCRIPTION
**Pull request by LefterisJP**

### CODE REVIEW

**Comment by andrevmatos** [comment]
Any specific reason why we can't use Infura? It may require some adaptation to the code which instantiates the `web3` session used (which gets a `config.json` from the node), but _should_ work, we may look into this

**Comment by LefterisJP** [comment]
Yeah we should definitely look into this. The only reason this note was added is that users in the hackathon were having CORS problems when trying to use Infura and the WebUI. 

But then 2 days ago @kelsos used the webui with Infura without any problems. Perhaps it's because the users were using OSX ... I don't know.

We should definitely look into this and adjust the docs accordingly.

**Comment by kelsos** [comment]
@andrevmatos In linux webui works without any problems with infura.

**Comment by ulope** [comment]
Didn't we plan at some point that we wanted to remove the need for the webui to connect to the eth node entirely?

**Comment by andrevmatos** [comment]
@ulope Not that I remember. WebUI will always need a lot more information than is relevant for the raiden API to provide (e.g. token symbol, name, etc), so we should always query eth rpc directly anyway. Today, we try to use the same eth-rpc-endpoint as Raiden, but that may not always be accessible (e.g. docker container, node in another host different from `localhost`, etc), so it falls back to `localhost`. We could improve these approaches in the future, but in theory, `Infura` supports CORS: https://github.com/INFURA/infura/issues/57

**Pull request merged**
