### PR TITLE
External secret resolver take two - Enhancments

### LINKED ISSUE #4039: Invalid LockedTransfer message - BUG
@rakanalh 
My setup has two raiden nodes A and B and a channel between them.

I'm sending from A to B:

first a transfer where A does not have the secret and B is not working with a resolver. This results in a `LockedTransfer` message from A to B. B respond with `SecretRequest` which is ignored by A. 
```
curl  -X POST http://localhost:$Aport/api/v1/payments/$token/$B -H 'Content-Type: application/json' --data-raw '{"amount": 2, "secret_hash": "0xa2abfe43b070b0f93b69441cec26290f20fda5c5b08e3a0a02d4674df348a270"}'
```

Next A is making a "regular" payment which ends ok.

```
curl  -X POST http://localhost:$Aport/api/v1/payments/$token/$B -H 'Content-Type: application/json' --data-raw '{"amount": 1}'
```

Next I **restart** A 

After the restart I try again a "regular" payment. This payment does not work.

```
curl  -X POST http://localhost:$Aport/api/v1/payments/$token/$B -H 'Content-Type: application/json' --data-raw '{"amount": 3}'
```
B's log shows this:
```
{
  "node": "133499f5",
  "raiden_events": [
    "{\"payment_identifier\": \"16919130081996907240\", \"reason\": \"Invalid LockedTransfer message. Balance proof's locksroot didn't match, expected: 0x9c8400c552dd8ff3ef2e84a81e6c4e6997f1203d82977827e7ebcc034e4543ca got: 0xbe13150d7acd878707ea5a2b0dac5ad341bd59473a29865e040cb23e576a9cca.\", \"_type\": \"raiden.transfer.events.EventInvalidReceivedLockedTransfer\", \"_version\": 0}",
    "{\"identifier\": \"16919130081996907240\", \"secrethash\": \"0x54386bef1ad37bc8919ce5c2d2b2111d85104e9589b77d8ceca4ddd7dedd5bef\", \"reason\": \"Invalid LockedTransfer message. Balance proof's locksroot didn't match, expected: 0x9c8400c552dd8ff3ef2e84a81e6c4e6997f1203d82977827e7ebcc034e4543ca got: 0xbe13150d7acd878707ea5a2b0dac5ad341bd59473a29865e040cb23e576a9cca.\", \"_type\": \"raiden.transfer.mediated_transfer.events.EventUnlockClaimFailed\", \"_version\": 0}"
  ],
  "event": "Raiden events",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "greenlet_name": "GMatrixClient._sync user_id:@0x133499f529a8d7cf00d8c5f7e73841ddb62b9ca3:raidentransport.ki-decentralized.com sync_token:s6022409_1452461_0_1_2084_1_1_26708_1",
  "timestamp": "2019-05-09 14:13:15.299488"
}
```

Looks like when the revents replaying at A restart something is not working as it was before. 
Let me know if you can spot it.

Thanks

Attached are 3 logs. 2 from A and 1 from B.
[raiden-debug_2019-05-09T14:09:50.118723.log](https://github.com/raiden-network/raiden/files/3162721/raiden-debug_2019-05-09T14.09.50.118723.log)
[raiden-debug_2019-05-09T14:02:17.182977.log](https://github.com/raiden-network/raiden/files/3162723/raiden-debug_2019-05-09T14.02.17.182977.log)

[raiden-debug_2019-05-09T14:02:53.524486.log](https://github.com/raiden-network/raiden/files/3162726/raiden-debug_2019-05-09T14.02.53.524486.log)

### PR DESCRIPTION
**Pull request by offerm**
This PR enhance handling when using resolver (secrethash is EMPTY):

- better handling or async_result to allow failure reason to be provided to the caller
- immediate return to the caller if the target is asking for the secret and the initiator does not have it. The payment request will stay inflight until expiration to make sure that the target really don't have the secret.
- verify secrethash when reusing payment_status
- make sure that the same secret hash will not be used by two (or more) parallel requests
- save and restore secrethash for TransferDescriptionWithSecretState. Fixes #4039

### CODE REVIEW

**Comment by rakanalh** [comment]
@offerm Is this PR something that you're still working on? if so, could you please rebase on top of the `develop` branch?

**Comment by offerm** [comment]
@rakanalh yes, still working on this one.   To complete the work we need sha256 support.

Please note that  https://github.com/raiden-network/raiden/pull/4031/commits/aa75e858688d3cd170dcc342847084378183d984 is solving a critical bug in latest master. Without it Raiden may not be able to restart.

**Comment by rakanalh** [comment]
On develop, we moved to dataclasses. So i think this is fixed on that branch.

But if i understand correctly, the fix is solving an issue for atomic swaps when the secrethash is given but no secret was assigned to the transfer, correct?

If that's the case, i don't think this is a critical issue (according to our definition) also provided that the integration between Raiden and UX is still WIP

**Comment by offerm** [comment]
I'm finalizing the integration this week. I hope to invite you for a quick demo soon. Afterthat we should discuss this PR.

Regardless, should I rebase on "develop" branch?
Should the PR be against "develop" branch or master?

**Comment by rakanalh** [comment]
We've recently split our branches as [explained here](https://github.com/raiden-network/raiden/blob/develop/docs/adr/0003-git-workflow.rst). So your branch will be merged to develop so you have to rebase it on top of develop

**Pull request closed without merging**
