### PR TITLE
Remove the extra " from the raiden command

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by palango** [comment]
Thanks for your PR @elopio  . We now have our CLA in place. Please rebase your PR, sign the CLA and add the `Please review` tag to this PR.

**Comment by elopio** [comment]
@palango I can't add tags to PRs.

**Comment by LefterisJP** [comment]
@elopio It's fine no worries. We will merge as soon as the tests pass.

**Comment by LefterisJP** [comment]
scratch that,this is just a docs change. I won't let Travis run on it.

One small thing to note. If it's just a docs change you can add `[skipci]` to the commit and Travis won't run.

**Pull request merged**
