### PR TITLE
setup.py python requires >= 3

### PR DESCRIPTION
**Pull request by hackaugusto**

### CODE REVIEW

**Comment by hackaugusto** [comment]
Since PR #1193 python2 is not supported.

@palango Do we have problems with versions bellow 3.5? Or we are just not running the build for other versions? https://github.com/raiden-network/raiden/pull/1193/files#diff-354f30a63fb0907d4ad57269548329e3R6

**Comment by LefterisJP** [comment]
Looks good to me. I think we just don't run the build for versions lower than 3.5. Travis is already rather overloaded.

**Comment by hackaugusto** [comment]
> I think we just don't run the build for versions lower than 3.5. Travis is already rather overloaded.

That is not my point. My question is: Do we have python specific requirements in the code that make it impossible to use versions prior to 3.5 (modules that are only available after 3.5? `typying` maybe), or is it just a coincidence that we are running tests with only that version?

If it is the case that versions prior to 3.5 cannot be used, we should reflect that in the selector and make stronger.

**Comment by LefterisJP** [comment]
I see. I have not tried with python 3 versions prior to 3.5 so perhaps @palango can chime in here.

**Comment by hackaugusto** [comment]
Ah, I just ahead and changed it to 3.5 becuase of the `typing` module

**Comment by palango** [comment]
Yeah, we need 3.5 for the `typing` module. And 3.4 only gets critical security fixes and is no longer maintained.

**Comment by ulope** [comment]
Strictly speaking even [3.5 is also already in security only release mode](https://devguide.python.org/#status-of-python-branches) but needlessly enforcing 3.6 seems premature right now (although we could use those shiny f-strings if we were...)

**Pull request merged**
