### PR TITLE
Move versions back into requirements file

### PR DESCRIPTION
**Pull request by palango**
Not having the versions in the `requirements` file caused problems in the services and also made it impossible for the GitHub dependency security checker to find issues.

### CODE REVIEW

**Comment by LefterisJP** [comment]
I totally support this. But can you also do the same for requirements-dev and lint?

**Comment by palango** [comment]
It's already like this there.

**Comment by LefterisJP** [comment]
@palango oh -- interesting.

**Comment by hackaugusto** [comment]
> versions in the requirements file caused problems in the services

Could you extend a bit on that? I believe the idea for not having the versions pinned in the requirements is exactly to support the usage of `Raiden` as a library (although that was never a high priority), right @ulope ?

Also, if we are going to stick with this change, doesn't it make sense to move all the constraints to the requirements file? This would make the development install a tad bit simpler

**Comment by palango** [comment]
So `pip`  doesn't use the `constraints`  file when we use raiden as a dependency, so we have to keep track of the versions of all packages Raiden uses and manually keep the same version in our requirements file. (This is because `setup.py` used the constraints file internally)

> Also, if we are going to stick with this change, doesn't it make sense to move all the constraints to the requirements file? This would make the development install a tad bit simpler

It might, I just wanted to make the minimal change necessary.

**Pull request merged**
