### PR TITLE
Mypy can only understand isinstance checks

### PR DESCRIPTION
**Pull request by LefterisJP**
This was prompted from the discussion made
[here](https://github.com/raiden-network/raiden/pull/3396#discussion_r253770360)

And the documentation of mypy also states that `isinstance()` checks
should be preferred for the same reason. [Source](https://mypy.readthedocs.io/en/latest/common_issues.html#complex-type-tests)

Also says it's "better style" whatever that means ...

### CODE REVIEW

**Comment by LefterisJP** [comment]
@hackaugusto So the reason you don't want this is since this code will break if at any point any of these state change classes inherit from one another at which point the order or `if ...elif..else` matters and can lead to bugs?

Damn .. then this is really a no-go.

But I don't like us having to have both a `type()` and an `isinstance()` check for each state transition. This should be redundant.

From the documentation of mypy I can't see why `type()` is not understood. It just says that it only knows about `isinstance()`

**Comment by LefterisJP** [comment]
I am closing this PR as we won't merge this. We can use it to continue the conversation as to what is the best solution for this problem.

**Comment by LefterisJP** [comment]
> A solution would be to use [singledispatch](https://docs.python.org/3/library/functools.html?highlight=dispatch#functools.singledispatch), it always choses the most concrete match (and would get rid of all that boilerplate as well)

And would typing work correctly with such an approach @ulope ?

**Comment by rakanalh** [comment]
@LefterisJP, @ulope:
```
from functools import singledispatch


class A:
    def __init__(self):
        pass


class B:
    def __init__(self):
        pass


class C(A):
    def __init__(self):
        pass


@singledispatch
def handler(arg):
    print(arg)


@handler.register
def handle_A(a: A):
    print("handle_A is called")


@handler.register
def handle_B(b: B):
    print("handle_B is called")


@handler.register
def handle_C(c: C):
    print("handle_C is called")


if __name__ == '__main__':
    a = A()
    b = B()
    c = C()

    handler(a)
    handler(b)
    handler(c)

```

Seems to work nicely in this simple example. The only problem we may have is that all handler functions should have the same exact signature, which is not always the case for the handlers we have.

**Comment by ulope** [comment]
@rakanalh The type specific implementations don't need to share the same parameter signature, the dispatching only happens on the first argument.
```python
from functools import singledispatch

@singledispatch
def handle(arg):
    print('base', arg)

@handle.register
def _(arg: int, another_arg):
    print('int', arg, another_arg)

@handle.register
def _(arg: bool):
    print('bool', arg)


handle('bla')
handle(1, 2)
handle(True)
```

```
base bla
int 1 2
bool True
```

**Comment by rakanalh** [comment]
oh... i missed this part in the docs. ok so if we actually want to apply this, our `handle_XXX` functions need to take the state_change first instead of the state object.

**Pull request closed without merging**
