### PR TITLE
Use JSON as a default logging format

### LINKED ISSUE #2939: Switch debug log to JSON
## Abstract

The debug log file is currently written in the human-readable text format.
Since it's mostly intended to aid debugging it makes more sense to log in JSON format.

## Motivation

The debug log is mostly useful for processing with tools. Having it in JSON format will make that much easier.

## Specification

Change the debug logger to produce JSON output

## Backwards Compatibility

It's a debugging feature, so not applicable.

### PR DESCRIPTION
**Pull request by rakanalh**
Resolves #2939

### CODE REVIEW

**Comment by LefterisJP** [comment]
Wouldn't it make more sense to make the debug log json only but keep the one that goes to stdout as it is?

**Comment by ulope** [comment]
Definitely, JSON on the console is close to unreadable.

**Comment by rakanalh** [comment]
@LefterisJP @ulope i agree but for some reason i thought my change would switch the log-file format configs. Anyway, i've only switched the debug log file to JSON formatting.

**Comment by LefterisJP** [comment]
@rakanalh looks good to me. Indeed debug log now has JSON but stdout logs are as before.

**Pull request merged**
