### PR TITLE
Add initial tmux transfer speed with pyflamer

### PR DESCRIPTION
**Pull request by utzig**
Creates a flame graph style profiler from a raiden node originating mediated transfers.

### CODE REVIEW

**Comment by czepluch** [comment]
Is this work in progress? Please add suiting label

**Comment by utzig** [comment]
@czepluch This could surely use some extra additions, like profiling all nodes, etc, but still it's a good start and doesn't impact any other sub-systems.

**Comment by LefterisJP** [comment]
@utzig Instead of merging master into your branch please consider always rebasing it on top of master. Makes for a much cleaner overall git history.

**Comment by utzig** [comment]
Things to make better: opening channels sometimes fail and there is no handling, the `pid` of the raiden process is not always caught by pyflamer depending on how long raiden takes to be launched.

**Comment by schmir** [comment]
This will not work with the current master branch, since raiden.app doesn't take a --privatekey argument anymore. In that case the python code is send to the shell (via tmux send-keys), which makes me think that this isn't an ideal solution to start a python program.

**Comment by hackaugusto** [comment]
Cant we reuse some of the scription code?  tools/tmux_transferspeed.sh  is mostly a copy-paste from  tools/tmuxtest.sh

**Comment by hackaugusto** [comment]
PR is abandoned, closing it.

**Pull request closed without merging**
