### PR TITLE
Transaction queue fixes

### PR DESCRIPTION
**Pull request by hackaugusto**
The previous implementation of the transaction queue was too restrictive. With the previous implementation if there were two transactions sent for the same purpose, e.g. two close transactions, the one that lost the race would not be removed from the queue, that was the case because only transactions sent by the local node were take into consideration, the strategy to fix that was to use additional state changes (implemented by https://github.com/raiden-network/raiden/pull/2049), but most of these are not necessary with this approach.

### CODE REVIEW

**Comment by rakanalh** [comment]
Reviewing this

**Comment by LefterisJP** [comment]
Also having a look as it was asked of me

**Comment by LefterisJP** [comment]
Wait a bit :P

**Comment by rakanalh** [comment]
@LefterisJP Yea am not merging until you've provided your review.

**Pull request merged**
