### PR TITLE
Add the packaging metadata to build the raiden snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest raiden in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

### CODE REVIEW

**Comment by palango** [comment]
Thanks for your PR @elopio  . We now have our CLA in place. Please rebase your PR, sign the CLA and add the `Please review` tag to this PR.

**Comment by LefterisJP** [comment]
@elopio Can you rebase instead of merging master into the PR? We want to have a clean commit history.

**Comment by elopio** [comment]
@LefterisJP sure, done.

**Comment by LefterisJP** [comment]
@elopio Thank you. Have not tested the snapcraft.yaml file to make a snap but other than that it looks good.

**Comment by elopio** [comment]
Thanks for the review @LefterisJP. What's great about this is that https://build.snapcraft.io publishes the snap in the edge channel of the store. In there, it is not visible to user searches so only the people helping with the tests will know its available to install.

We usually make a [call for testing](https://forum.snapcraft.io/search?q=call%20for%20testing) to gather feedback from the community before publishing snaps to stable and exposing them to users. Let me know if you would like to do that, I'd be happy to help.

**Pull request merged**
