### PR TITLE
Use raiden-contracts v0.16.0 and remove the temporal fix

### PR DESCRIPTION
**Pull request by pirapira**
Upgrading raiden-contracts to v0.16.0.  I should be able to remove the temporal fix in https://github.com/raiden-network/raiden/pull/3674 .

### CODE REVIEW

**Comment by LefterisJP** [comment]
@pirapira you can't just upgrade the contracts version without making the proper changes to the startup code to use the new functions :)

**Comment by pirapira** [comment]
I'm trying to see a failure.  A local `make test` didn't work for [an unrelated reason](https://github.com/raiden-network/raiden-contracts/issues/783).

**Comment by pirapira** [comment]
Actually, since I kept the old function with the old API, the tests might just go through.

**Comment by LefterisJP** [comment]
> Actually, since I kept the old function with the old API, the tests might just go through.

Aha that's why. 

Also ... we don't have sufficient tests for the startup at the moment: https://github.com/raiden-network/raiden/issues/3677

**Pull request merged**
