### PR TITLE
add udc too low scenario [skip tests]

### PR DESCRIPTION
**Pull request by czepluch**
This implements the first of the scenarios in https://github.com/raiden-network/raiden/issues/4593

### CODE REVIEW

**Comment by czepluch** [comment]
@Dominik1999 I don't but I know that the default is much lower than `5 * 10 ** 18`. If you want I can be more implicit (probably a good idea in case we change default behaviour).

**Comment by Dominik1999** [comment]
> @Dominik1999 I don't but I know that the default is much lower than `5 * 10 ** 18`. If you want I can be more implicit (probably a good idea in case we change default behaviour).

ah ok that makes sense. but what I meant is, how can we ensure in that scenario that the node has less than 5 * 10 ** 18 tokens ?

**Comment by czepluch** [comment]
Ah, so you mean over time assuring it? I think the `max_funding` can take care of that and then never allow it to be above the minimum price for monitoring.

**Comment by czepluch** [comment]
@Dominik1999 please take another look. Added `max_funding`.

**Comment by agatsoh** [comment]
Looks good to me!!!

**Comment by czepluch** [comment]
@agatsoh could you then please approve the PR? :)

**Pull request merged**
