### PR TITLE
simpler create_default_identifier

### PR DESCRIPTION
**Pull request by hackaugusto**

### CODE REVIEW

**Comment by LefterisJP** [comment]
@hackaugusto Should be fine for the way idehtifiers need to be used. But I can't recall why we had such a complicated Spec for the default identifier in the first place. Any ideas?

**Comment by hackaugusto** [comment]
I don't know, the logic for the identifier was added by: 8b7d0be65abc9ba1aca8149de5fa91ae8b26f73b

**Comment by LefterisJP** [comment]
And here is the issue: https://github.com/raiden-network/raiden/issues/139

I don't remember why we went with this design. Perhaps it was an offline discussion.
@konradkonrad do you remember?

**Comment by hackaugusto** [comment]
So, if this is merged, should we use `random.randint(0, UINT64_MAX)` or `int(sha3(random.randint(0, UINT64_MAX)), 16)`?

The previous is leaking the mersenne PRNG internal state, and since it's part of the identifier it seems trivial to get the internal state, the `sha3()` should protect against that but is a bit more crypt.

**Comment by konradkonrad** [comment]
@hackaugusto 
> python2.7 seeds random with the current time stamp, the key space is minimal, brute forcing is trivial.

that is only the case if `os.urandom` isn't available (which would be a blocker for hashlocks anyway). why not just use `random.SystemRandom` to be on the safe side?

**Comment by hackaugusto** [comment]
> that is only the case if os.urandom isn't available

What you mean? [`random.random` is always initialized with the current time stamp](https://github.com/python/cpython/blob/2.7/Lib/random.py#L881-L889)

> why not just use random.SystemRandom to be on the safe side?

[random.SystemRandom is a wrapper for os.urandom](https://github.com/python/cpython/blob/2.7/Lib/random.py#L807-L837), either interface seems good to me

**Comment by LefterisJP** [comment]
I am fine with the simplification of the default identifier.

**Pull request merged**
