### PR TITLE
update coincurve

### PR DESCRIPTION
**Pull request by ofek**
https://github.com/ofek/coincurve#changelog

### CODE REVIEW

**Comment by ulope** [comment]
Thanks for the PR @ofek. 
We're currently hard at work getting the developer preview release ready. That means that we currently try to avoid everything that could cause delays in that (for example upgrading dependencies).

We will gladly accept this PR but only after we've released the dev preview.

**Comment by ofek** [comment]
@ulope Understood, thanks! Just to be clear, Coincurve 5.0.1 patched a bug.

**Comment by ofek** [comment]
@ulope I think this can be merged now.

**Comment by palango** [comment]
Thanks for your PR @ofek . We now have our CLA in place. Please rebase your PR, sign the CLA and add the `Please review` tag to this PR.

**Comment by ofek** [comment]
@palango @ulope I don't have permission to add labels.

**Comment by LefterisJP** [comment]
@ofek No worries, disregard the comment about the label. But can you rebase so that there is only 1 commit?

**Pull request merged**
