### PR TITLE
Add FAQ in the onboarding document

### PR DESCRIPTION
**Pull request by pirapira**
The first entry is "what is MS/PFS".  I thought about describing them more, but that would be a duplicate of the glossary in the spec.

I'll add more entries.

### CODE REVIEW

**Comment by BOR4** [comment]
@pirapira I see you added some future features to FAQ in this pull request. Maybe [this list ](https://raiden.network/roadmap.html) of AFAIK all the planned future features except maybe "light client" expands your idea what should go to FAQ.

**Comment by pirapira** [comment]
@BOR4 If I say "it's a feature planned in the future" in this PR, it's good to merge?  I saw "MS" and "PFS" in many places and had no idea what they were.

**Comment by BOR4** [comment]
@pirapira it sounds good to me, but I am not really the right person to make that decision.

**Comment by pirapira** [comment]
@BOR4 Thank you.  I wanted to know what you meant.

**Pull request merged**
